POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "test",
    "password": "test123"
}


###

POST http://localhost:8080/revalidate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9pZCI6Ik5ld3Rlc3QiLCJzdGF0dXMiOiJBIiwibGFzdF9sb2dpbiI6IjIwMjEtMDItMDlUMTg6Mjg6MzYuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDIxLTAyLTA4VDEwOjU5OjU2LjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMi0wOVQxODoyODozNi4wMDBaIiwiaWF0IjoxNjEyODk3ODk0LCJleHAiOjE2MTI4OTk2OTR9.5ztbRCJ03hNLJmPyvWzCxEmsUyv1s5hVnlIk4teexiY

###

POST http://localhost:8080/products/create
content-type: application/json

{
    "name": "Test Prod",
    "category": 0,
    "description": "test product",
    "upc": "123456789",
    "unint_price": 10,
    "weights": "POUNDS",
    "prouct_image": "https://images-na.ssl-images-amazon.com/images/I/91j3Eaf3BZL._SX569_.jpg",
    "ingreedents_image": "https://d2s8edsvfzlfgk.cloudfront.net/images/detailed/10/image_43_ofhb-49.jpg?t=1579667917",
    "upc_image": "https://jet-marking.com/wp-content/uploads/2017/04/pasted-image-0-1.png"
}




###

GET http://localhost:8080/getAllMerchants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcl9pZCI6Im1haWxAZW1haWwuY29tIiwic3RhdHVzIjoiQSIsImxhc3RfbG9naW4iOiIyMDIxLTAyLTA3VDE4OjQ0OjM0LjAwMFoiLCJjcmVhdGVkX2F0IjoiMjAyMS0wMi0wNlQxNTo0ODo0Mi4wMDBaIiwidXBkYXRlZF9hdCI6IjIwMjEtMDItMDdUMTg6NDQ6MzQuMDAwWiIsImlhdCI6MTYxMjcyNjY0OCwiZXhwIjoxNjEyNzI4NDQ4fQ.-roVxdvIV5wtwJPNSOI3G0FUGYfte6eRCMk3KhQUwQU

GET http://localhost:8080/merchant/getmerchants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9pZCI6Ik5ld3Rlc3QiLCJzdGF0dXMiOiJBIiwibGFzdF9sb2dpbiI6IjIwMjEtMDItMDlUMTg6Mjg6MzYuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDIxLTAyLTA4VDEwOjU5OjU2LjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMi0wOVQxODoyODozNi4wMDBaIiwiaWF0IjoxNjEyODk3ODk0LCJleHAiOjE2MTI4OTk1NzR9.GITqnLDopCOez-29Y4LPFxMcjj15z4aCS2PJC3CKbLM

###
POST http://localhost:8080/merchant/delete
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9pZCI6Ik5ld3Rlc3QiLCJzdGF0dXMiOiJBIiwibGFzdF9sb2dpbiI6IjIwMjEtMDItMDlUMTg6Mjg6MzYuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDIxLTAyLTA4VDEwOjU5OjU2LjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMi0wOVQxODoyODozNi4wMDBaIiwiaWF0IjoxNjEyODk3ODk0LCJleHAiOjE2MTI4OTk1NzR9.GITqnLDopCOez-29Y4LPFxMcjj15z4aCS2PJC3CKbLM

{
    "userid" : 100
}

###

POST http://localhost:8080/merchant/update
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9pZCI6Ik5ld3Rlc3QiLCJzdGF0dXMiOiJBIiwibGFzdF9sb2dpbiI6IjIwMjEtMDItMDlUMTg6Mjg6MzYuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDIxLTAyLTA4VDEwOjU5OjU2LjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMi0wOVQxODoyODozNi4wMDBaIiwiaWF0IjoxNjEyODk3ODk0LCJleHAiOjE2MTI4OTk1NzR9.GITqnLDopCOez-29Y4LPFxMcjj15z4aCS2PJC3CKbLM

{
    "id":3,
    "description" : "This is the updated description",
    "logo" :"req.body.logo",
    "address": "a3",
    "city" : "req.body.address",
    "zipcode" : "z3",
    "country" : "countryname",
    "latlang" : "req.body.latlang",
    "email" : "testmail",
    "phone" : "req.body.phone"

}

###

POST http://localhost:8080/merchant/create
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9pZCI6Ik5ld3Rlc3QiLCJzdGF0dXMiOiJBIiwibGFzdF9sb2dpbiI6IjIwMjEtMDItMDlUMTg6Mjg6MzYuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDIxLTAyLTA4VDEwOjU5OjU2LjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMi0wOVQxODoyODozNi4wMDBaIiwiaWF0IjoxNjEyODk3ODk0LCJleHAiOjE2MTI4OTk1NzR9.GITqnLDopCOez-29Y4LPFxMcjj15z4aCS2PJC3CKbLM

{
    "user_id": "10",
    "business_name" : "Harish Store",
    "description" : "This is my store",
    "logo" :"https://www.exchange4media.com/news-photo/1524021329_Vr74ME_bigbasket-logo.jpg",
    "address": "my location",
    "city" : "my city",
    "country" : "my contry",
    "latlang" : "17.467843, 78.358580",
    "email" : "mail@email.com",
    "zipcode":500080,
    "phone" : "7801070710",
    "contact_person" : "Harishkumar",
    "username": "harish@email.com",
    "password": "password"
}

###
POST http://localhost:8080/merchant/search
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9pZCI6Ik5ld3Rlc3QiLCJzdGF0dXMiOiJBIiwibGFzdF9sb2dpbiI6IjIwMjEtMDItMDlUMTg6Mjg6MzYuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDIxLTAyLTA4VDEwOjU5OjU2LjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMi0wOVQxODoyODozNi4wMDBaIiwiaWF0IjoxNjEyODk3ODk0LCJleHAiOjE2MTI4OTk1NzR9.GITqnLDopCOez-29Y4LPFxMcjj15z4aCS2PJC3CKbLM

{
    "value" : "a3"
}
###

GET http://localhost:8080/users/getusers?limit=6&offset=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9pZCI6Ik5ld3Rlc3QiLCJzdGF0dXMiOiJBIiwibGFzdF9sb2dpbiI6IjIwMjEtMDItMDlUMTg6Mjg6MzYuMDAwWiIsImNyZWF0ZWRfYXQiOiIyMDIxLTAyLTA4VDEwOjU5OjU2LjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMi0wOVQxODoyODozNi4wMDBaIiwiaWF0IjoxNjEyODk3ODk0LCJleHAiOjE2MTI4OTk1NzR9.GITqnLDopCOez-29Y4LPFxMcjj15z4aCS2PJC3CKbLM

###

POST http://localhost:8080/users/create
content-type: application/json

{
    "user_id":"test",
    "password":"test123"
}


